### ISSUE TITLE
MVP Suggestions

### ISSUE THREAD

**Issue by brtrick** [huangs2022672/depth-of-field#1]
MVPs are looking good! Very thorough. Just a couple comments:     
1. Consider moving Albums up to number 4, after Photos. It's probably going to be more complex than the other two.
2. Follows and comments are really two separate things. I recommend moving follows to the bonus section. You can always add it in later if you finish everything else.

**Comment by huangs2022672** [comment]
Thanks Brad! After working on the schema, I realized there's a lot (maybe too much) I can do with this project. I've updated the MVP list, but I'll probably come back and make more updates later on.
