### ISSUE TITLE
Sample State suggestions

### ISSUE THREAD

**Issue by brtrick** [huangs2022672/depth-of-field#3]
Good job with the sample state! A few suggestions:
1. Not clear if "joined" is a field that is included in the short form of user or not (32 has it, 41 does not). (Then again, Miyazaki is timeless...)
2. Comment information is stored twice: comments includes a photo_id, and photo includes an object of associated comments. You don't need the latter. (Just use a selector to go through the comments in state and grab the ones with the id of the photo you are interested in.)
3. Same issues with albums and photos: the info about the association is in the state twice, once under albums and once under photos. (Want to avoid this because when information is stored more than once, it can get out of sync.)
4. You probably will want to store the image url for a photo in your state.
5. I'm not sure what "liked" signifies under photos. Is that whether or not the current user likes the photo? If so, that will require a lot of upkeep to implement that way. (Think about when someone new logs in.)
6. Probably want to store the status of the "private" bool in photos.
7. For lists of ids, use an array instead of an object (comments under photos, photos under albums, etc.)

In answer to your question, we can track info that comes through associations, but it might get stored in different parts of the state. JBuilder helps us set that up.

**Comment by huangs2022672** [comment]
1. took me a sec to remember why I wrote it this way. but I used the yipper Sample State as a reference and it said that "There might be different information for each user depending on how the current user has interacted with them". I'm going to update my Sample state with notes that explain this.

2. thanks, my question about association wasn't phrased correctly, but it was in reference to this: whether associated data should be nested, i.e. comments be nested in photos. I've removed comments from photo and keeping a comments slice.

3. Removed album_id from photos and updated photos in album to be an array of photo's ids. 

4. added image url to photos slice.

5. Yes, liked signifies if the current user has liked the photo or not. is there another way to implement this? if I go to a photo's show page or hover over a photo in an index page, I'd like to see a heart/star filled-in that signifies if I've previously liked the photo. Would a likes slice of state work?

6. added private to photos

7. done!

**Comment by brtrick** [comment]
Good work. To answer your questions:
1. Yes, storing an array of liked photos in the session slice of state would probably be a better way to store that information. Then if a user logs in/out, you can just reset that one array instead of having to go through (or reload) every photo in state and change the "liked" field twice (once on logout and then again on log in).
2. The array of photos in albums will work well if/when you get to albums. Just FYI, the other way you could store that info would be to have a slice of state for your joins table.

Closing.
