### ISSUE TITLE
Front-end routes suggestions

### ISSUE THREAD

**Issue by brtrick** [huangs2022672/depth-of-field#4]
Good job with the front-end routes! A couple notes/questions:
1. Don't worry about mobile. Resizing would be a bonus after you have finished everything else. Moving to mobile would be beyond even that. (e.g., mobile users don't have a mouse, so you would have to adjust to touch controls).
2. Note that Flickr actually takes you to a different page from the splash page for login and signup. (i.e., it is not just a modal that pops up.)
3. Decide whether you want to use /explore or /photos for the photos index
4. I realize this is bonus now, but do you intend /albums to return all albums in the app or all albums associated with a given user?

**Comment by brtrick** [comment]
Also, minor point, but you might want to add a : before the ids in your routes to indicate they are wildcards.

**Comment by brtrick** [comment]
One more thing: you might want to add a photos/upload route.

**Comment by huangs2022672** [comment]
1. got it
2. I've seen others implement them as a modal and would like to do this as well. what do you think? if going w/ modal, I guess I won't need /signup /login? 
3. ok, going with "/explore"
4. it should be all albums of a user
5.  done
6.  done

**Comment by brtrick** [comment]
Looks good! Closing.
